language: node_js
node_js:
  - lts/*
services:
  - docker

before_install: 
  - docker build -t niass/docker-react -f Dockerfile.dev .

scripts:
  - docker run niass/docker-react npm run test -- --coverage