language: node_js
node_js:
  - lts/*
services:
  - docker

before_install: 
  - docker build -t niass/docker-react -f Dockerfile.dev .

scripts:
  - docker run niass/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-840250866699"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
      secure: "$AWS_SECRET_KEY"
